# -*- coding: utf-8 -*-
"""beer_20220928.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZ-W_GsdEcWKv71aTPDx66-J2T-uhgoT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import io

data_csv = pd.read_csv("https://raw.githubusercontent.com/jamesrobertlloyd/gp-structure-search/master/data/raw/TSDL/monthly-beer-production-in-austr.csv")

data_csv.columns

data_csv.rename(columns = {'Monthly beer production in Australia: megalitres. Includes ale and stout. Does not include beverages with alcohol percentage less than 1.15. Jan 1956 ? Aug 1995' : 'beer'}, inplace = True)

data_csv

print(data_csv)

data_csv.info()

len(data_csv)

alpha = 0.7
n_samples = 477
time_end = 10

dt = time_end / n_samples
time = np.arange(0,time_end,dt)
x_meas_save = np.zeros(n_samples)
x_esti_save = np.zeros(n_samples)
x_avg_save = np.zeros(n_samples)

data=data_csv["beer"]

def low_pass_filter(x_meas, x_esti,m_alpha):
    """Calculate average sonar using a low-pass filter."""
    x_esti = m_alpha * x_esti + (1 - alpha) * x_meas
    return x_esti

def average(k, x_avg_k_1, x_measure):
    alpha = (k-1)/k
    x_avg_k = alpha * x_avg_k_1 +(1-alpha)*x_measure
    return x_avg_k

x_esti = None
x_avg = 0
for i in range(n_samples):
    x_meas = data[i]
    k = i + 1
    x_avg = average(k, x_meas, x_avg)
    if i == 0:
        x_esti = x_meas
    else:
        x_esti = low_pass_filter(x_meas, x_esti, alpha)

    x_meas_save[i] = x_meas
    x_esti_save[i] = x_esti
    x_avg_save[i] = x_avg

plt.plot(time, x_meas_save, 'r*', label='Measured')
plt.plot(time, x_esti_save, 'b-', label='Low-pass Filter')
plt.legend(loc='upper left')
plt.title('Measured Altitudes v.s. LPF Values')
plt.xlabel('Time [sec]')
plt.ylabel('Altitude [m]')
plt.savefig('/png')