# -*- coding: utf-8 -*-
"""matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exN3j_jQT8x8WNbx5cNC-e50vCX7M66D
"""

import numpy as np

d_array = np.array([[2, 5], 
                    [1,3]])
print(d_array)

d_array_det = np.linalg.det(d_array)

print(d_array_det)

d_array_inv = np.linalg.inv(d_array)

print(d_array_inv)

d_array = np.array([[2,5], [1,3]])
print(np.transpose(d_array))
print(d_array.transpose())
print(d_array.T)

import numpy as np

x  = np.arange(9).reshape(3, 3)
print(x)

np.diag(x)

np.diag(np.diag(x))

b = np.arange(16).reshape(4, 4)

print(b)

np.trace(b)

